### PR TITLE
4.9.1

### PR DESCRIPTION
**Pull request by minimum2scp**
Created with `npm run submit-definitions`.

### CODE REVIEW

**Comment by jasonkarns** [comment]
@minimum2scp you want commit bit?

**Comment by minimum2scp** [comment]
@jasonkarns Oh, really?
Can I merge pull request that adds definition of new nodejs version without your review?

**Comment by jasonkarns** [comment]
Yeah, if you're interested, I'll add you as a contributor.

**Comment by minimum2scp** [comment]
Thank you, I want commit bit!

**Pull request merged**
