### PR TITLE
Add definition for Node 6.1.0

### PR DESCRIPTION
**Pull request by sds**
This was released May 5, 2016. Add it so eager users can easily get their hands on it!

### CODE REVIEW

**Comment by jawshooah** [comment]
Thanks! :beers:

**Comment by sds** [comment]
Sweet, thanks for the quick merge!

What's the policy on tagging new releases? Right now if I want to install this via a Homebrew-installed `node-build`, I have to `brew upgrade node-build --HEAD`. 

If we tag a release I can then submit a PR to `homebrew-core` that updates https://github.com/Homebrew/homebrew-core/blob/ee6ed31da5/Formula/node-build.rb to point to the latest release, saving us from needing `--HEAD`.

**Comment by jawshooah** [comment]
It seems the pattern so far has been to push a patch release after adding a new version of Node. I've done just that, and opened Homebrew/homebrew-core#947.

**Comment by jasonkarns** [comment]
So far, I've just been doing patch releases for new build defs, since they aren't api-breaking changes to node-build itself. They don't really qualify as bug fixes, either. Though I suppose they could arguably be pushed as minor updates (new features).

**Comment by jasonkarns** [comment]
Also, @sds reminder that if you install node-build as a plugin (instead of through homebrew) by git-cloning into $(nodenv root)/plugins, then you can get the latest node-build definitions by doing a git-pull. This avoids the delay between when node-build is updated and when the version is bumped in homebrew. (Throw in the [nodenv-update](https://github.com/nodenv/nodenv-update) plugin and you can update all git-installed nodenv plugins via `nodenv update`)

Also, I recommend the [node-build-update-defs](https://github.com/nodenv/node-build-update-defs) plugin which will run the scraper and generate latest build definitions (local to your machine) before they even make it into node-build. This plugin is actually how we generate new definitions for node-build itself: https://github.com/nodenv/node-build/blob/master/package.json#L27

**Pull request merged**
