### PR TITLE
Travis: only test against master

### PR DESCRIPTION
**Pull request by jawshooah**
[Review on Reviewable](https://reviewable.io/reviews/nodenv/node-build/109)

### CODE REVIEW

**Comment by jasonkarns** [comment]
how does this affect travis running the tests on PRs?

Also note, Travis has a bug where single-commit branch builds will error out because the `TRAVIS_COMMIT_RANGE` var is empty  https://github.com/travis-ci/travis-ci/issues/5133

**Comment by jawshooah** [comment]
> how does this affect travis running the tests on PRs?

It doesn't. It just disables `push` builds for branches other than `master`, which shouldn't be necessary.

**Comment by jasonkarns** [comment]
cool. as long as we still get a PR build, i'm happy. And nice side effect
of avoiding the known-broken push builds from Travis.

**Comment by jawshooah** [comment]
Should also note that `TRAVIS_COMMIT_RANGE` is broken in more ways than one, which is why the PR build is failing. Here's how we [work around it](https://github.com/caskroom/homebrew-cask/blob/f57ef580f851d77763dbf21621c4bc3a66a74978/ci/travis/before_install.sh#L21-L27) in homebrew-cask.

**Pull request merged**
