### PR TITLE
6.17.1

### PR DESCRIPTION
**Pull request by minimum2scp**
Created with `npm run submit-definitions`.

### CODE REVIEW

**Comment by minimum2scp** [comment]
CI failed.
https://travis-ci.org/nodenv/node-build/jobs/516251301

```
not ok 54 definitions have EOL and LTS warnings
# (from function `assert_output' in file test/../node_modules/bats-assert/src/assert.bash, line 255,
#  in test file test/eol-lts.bats, line 11)
#   `assert_output ""' failed
# 
# -- output differs --
# expected (0 lines):
# 
# actual (17 lines):
#   11.0.0
#   11.1.0
#   11.10.0
#   11.10.1
#   11.11.0
#   11.12.0
#   11.13.0
#   11.2.0
#   11.3.0
#   11.4.0
#   11.5.0
#   11.6.0
#   11.7.0
#   11.8.0
#   11.9.0
#   11.x-dev
#   11.x-next
```

Node 11 is in maintenance from 2019-04-01.

- https://nodejs.org/en/about/releases/
- https://github.com/nodejs/Release

**Comment by jasonkarns** [comment]
The tests are smart enough to pull the LTS info from nodejs.org (https://github.com/nodenv/node-build/blob/master/test/helpers/warning_messages), but aren't configured to run on a scheduled timer. So whenever a node transitions to a different mode, the tests don't blow up until whatever happens to trigger the next test run :/

Force regenerating the definitions should re-write the 11.x defs to include the maint-mode warning. ( can do later tonight if you don't get a chance.)

**Comment by jasonkarns** [comment]
Requesting some clarification from node release team: https://github.com/nodejs/Release/issues/431

According to the release schedule.json (which drives the test check), we are in a release dead zone. 11.13.0 is considered maintenance mode, but it's also the Current Release (12 isn't considered current until 4-23)

**Comment by jasonkarns** [comment]
handled by #482

**Comment by minimum2scp** [comment]
Thanks!

**Pull request closed without merging**
