### PR TITLE
Restore mirror capability

### PR DESCRIPTION
**Pull request by jasonkarns**
node-build will not provide a default mirror, but this PR at least restores the ability to select a mirror from which to download packages.

- [x] fix 2 failing tests
- [x] fix mirror_url formulation (currently follows ruby's mirror url format, which is $mirror_host/$checksum. Needs to be a regular mirror copying full url structure. see https://github.com/nodenv/node-build/pull/208#issuecomment-260416775

closes #208

### CODE REVIEW

**Comment by jasonkarns** [comment]
@dochang  Here's the restoration of the original mirror feature. If you are able, we need to first get the tests passing in this branch. I'm 99% sure the code is correct and that it's the tests that aren't correct. PRs welcome (opened against this branch) to fix the tests so that they pass.

Once the tests are green, we'll change functionality so that it doesn't rely on ruby's mirror_host/checksum format.

Cool?

**Comment by jasonkarns** [comment]
tests green! time to fix formulation of mirror URL

**Comment by jasonkarns** [comment]
@dochang would you be able to verify whether this PR works for you? Also, could you share all of the nodejs mirrors (and their respective URL structures) that you're aware of?

**Comment by dochang** [comment]
It works here, Thank you! Please merge it!

Here are all mirrors I found:

- https://mirrors.ustc.edu.cn/node/
- https://npm.taobao.org/mirrors/node
- https://cnpmjs.org/mirrors/node/
- http://npm.mirrors.cqupt.edu.cn/dist/node
- http://nodejs.serverpals.com/dist/

**Pull request merged**
