### PR TITLE
Automatically maintain release notes using GitHub Actions

### PR DESCRIPTION
**Pull request by minimum2scp**
@jasonkarns 
How about using [Release Drafter](https://github.com/marketplace/actions/release-drafter)?
I think Release Drafter will help your release task.

### CODE REVIEW

**Comment by minimum2scp** [comment]
Release workflow is added by #533, so it seems that this PR is no longer necessary.

**Comment by jasonkarns** [comment]
I'd like to keep this open. #533 does a hacky job of generating the release notes, and I'd prefer to replace the `script/release-notes` script with an action that does the job better.

I'm not sure if we'd use Release Drafter (which seems to incrementally build up the release notes?) or another action that builds the notes at the time of release.

**Comment by jasonkarns** [comment]
Do you know what the release process would be like if we used this action? As the notes accumulate on a draft release, how does the final release get moved from Draft to Published?

And what happens with the version number when it's finally published? It appears that the action defaults to speculatively using "NEXT_PATCH" as the version number... But what happens when we do a minor or major version bump?

**Comment by minimum2scp** [comment]
Release Drafter just creates or updates a draft release after every push to master branch,
and the version number is expanded in the draft release.
(please check https://github.com/toolmantim/release-drafter for details)

So, when you want the draft release make publish, your workflow will be:

1. open the release page on github 
2. edit release name, tag name and contents (if you want)
3. and then `Publish Release` button

NOTE: tag name might be `untagged-<HASH>` in the draft release (https://github.com/toolmantim/release-drafter/issues/204), 
so please be careful about tag name in the draft release.

**Comment by minimum2scp** [comment]
> NOTE: tag name might be `untagged-<HASH>` in the draft release ([release-drafter/release-drafter#204](https://github.com/release-drafter/release-drafter/issues/204)),
> so please be careful about tag name in the draft release.

This problem is fixed by [release-drafer v5.6.0](https://github.com/release-drafter/release-drafter/releases/tag/v5.6.0).

**Comment by jasonkarns** [comment]
I'm closing this for now. My main concern with release-drafter is that it requires manual steps to publish the draft release. Presently, the process of releasing is all automated via github actions. I'm not really stoked about adding a manual step that must be done after the automated portions are complete.

Current flow:

1. run `npm version <bump>` from CLI
2. version is bumped, git-tagged, and pushes to github
3. the pushed tag triggers the release workflow action
    a. opens PR to bump the homebrew formula
    b. publishes npm package to npm registry
    c. publishes a Release on github

I have two concerns with Release Drafter. Firstly, how do we ensure that the _automated_ release publishing that is done in step 3c uses the draft release built-up by release drafter? If this concern can be addressed, I'd feel better.

And then how does the release get published automatically? I don't want a manual step to be necessary that must follow step 3 above; especially because that manual step would need to wait until all the automated steps were complete.

If both of these concerns can be addressed somehow, then I'm on board!

**Comment by jasonkarns** [comment]
Note that https://github.com/release-drafter/release-drafter/pull/424 may address some of these concerns.

**Comment by jasonkarns** [comment]
> I'd like to keep this open. #533 does a hacky job of generating the release notes, and I'd prefer to replace the `script/release-notes` script with an action that does the job better.
> 
> I'm not sure if we'd use Release Drafter (which seems to incrementally build up the release notes?) or another action that builds the notes at the time of release.

Following up on this: we now use github's api for creating releases that has `--generate-notes` so we don't need any additional tooling like release-drafter.

**Pull request closed without merging**
